#+TITLE: Personal Portfolio
#+OPTIONS: toc:nil

* Personal Portfolio
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+TOC: headlines

* Under Construction
This readme will become more extensive in the future.

* Design Goals
- Look clean and attractive
- Display well on all screen sizes
- Have some personality
- Make useful information available quickly
- Don't be excessive or overblown

* Creating content
Currently, all content is exported from a single Org file at
=org/content.org=. The =ox-hugo= package exports as many Org subtrees
as desired to their own Hugo compatible Markdown files. The section,
category, tags, and name of the export file may all be set, as well as
many other per file options. Managing all site content from a single
file is significantly easier than having to deal with many.

Page title is determined by top level headline of subtree to be
exported. Lower level headlines become lower level headings. The
layout is determined by the section the page is part of, although
layouts can be extremely granular as necessary. Dynamically generated
content is accomplished using the Hugo shortcodes system to insert
HTML snippets.

* Generating the site
- Run =make deploy= to regenerate the site in =public= and deploy it
  immediately to the GitHub repository that serves the site.
- Run =make publish= to have the site generated by Hugo and placed in
  the =public= directory.
- Run =make serve= to serve the site on port 1313 of all interfaces,
  to review before deploying.
- Run =make clean= to remove all files generated by the Org export and
  by Hugo publishing.

* To do
- [ ] Format the readme properly
- [ ] Collapsible tables of contents?

* Future
- Showcase pages for each important project

